name: Logs from Lille Ã˜
author: meri-imperiumi
map_style: outdoor-v2
defaults:
  - scope:
      path: ""
      type: logs
    values:
      layout: log
  - scope:
      path: ""
      type: years
    values:
      layout: year
collections:
  logs:
    output: true
    permalink: /:name/
    sort_by: created
  years:
    output: true
    permalink: /:name/
  crew:
    permalink: /:name/
  texts:
    output: false
  videos:
    output: false
exclude:
  - fetchais.mjs
  - .github
  - .gitignore
  - README.md
  - package.json
  - package-lock.json
  - node_modules
